<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <!--Publish Package START-->
    <PropertyGroup>
        <PackageId>LTs.Configurations</PackageId>
        <Version>8.0.0-preview1</Version>
        <Authors>LTsoft</Authors>
        <Description>LTs.Configurations</Description>
        <Copyright>Copyright 2026</Copyright>
        <RepositoryUrl>https://github.com/LTsoft-repo/LTs.Utils.git</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <DebugType>embedded</DebugType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
    <!--Publish Package END-->

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.KeyPerFile" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LTs.DependencyInjections\LTs.DependencyInjections.csproj" />
        <ProjectReference Include="..\LTs.Utils\LTs.Utils.csproj" />
    </ItemGroup>

</Project>
